/**
 * Simple Task Manager
 * Task Manager
 *
 * OpenAPI spec version: 1.0.0
 * Contact: scrtestingpurposes@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("AdminsApi", () => {
  let instance: api.AdminsApi
  beforeEach(function() {
    instance = new api.AdminsApi(config)
  });

  test("deleteTask", () => {
    const taskId: string = "taskId_example"
    return expect(instance.deleteTask(taskId, {})).resolves.toBe(null)
  })
  test("postTask", () => {
    const body: api.Task = undefined
    return expect(instance.postTask(body, {})).resolves.toBe(null)
  })
})

describe("UsersApi", () => {
  let instance: api.UsersApi
  beforeEach(function() {
    instance = new api.UsersApi(config)
  });

  test("getTasks", () => {
    const skip: number = 56
    const limit: number = 56
    return expect(instance.getTasks(skip, limit, {})).resolves.toBe(null)
  })
})

